Jonathanguven/issue8
SCE-Development/sjsu-rmp pull request #13
Opened 2024-03-13 14:06 UTC by jonathanguven

- Created user and session table
- Created Drizzle adapter for lucia
- Implemented Lucia sessions
- Implemented google oauth using arctic
- created login and logout buttons
- created root route form actions for testing

2024-03-13 17:22 UTC, gursheyss requested changes

2024-03-13 17:22 UTC, gursheyss commented on src/routes/+page.server.ts
> +};
Instead of returning loggedIn we can just return the user if it exists and change our component  so it only renders if user exists
```suggestion
export const load: PageServerLoad = async (event) => {
	if (event.locals.user) {
		return {
			user: event.locals.user,
		};
	}
};
```

2024-03-13 17:22 UTC, gursheyss commented on src/routes/+page.svelte
> +{#if data?.loggedIn}
```suggestion
{#if user}
```

2024-03-13 17:22 UTC, gursheyss commented on src/routes/auth/+server.ts
> +const { DEV } = process.env;
```suggestion
import { dev } from '$app/environment';
```

2024-03-13 17:22 UTC, gursheyss commented on src/routes/+page.server.ts
> +	}
We don't need this, just move the auth/+server.ts logic into here and return the Google url directly from the form action

2024-03-13 17:22 UTC, gursheyss commented on src/routes/auth/callback/+server.ts
> +		const googleUser = await response.json();
```suggestion
		const { name, email, sub: googleId } = await response.json();
```

make sure to change the parts this is used too

2024-03-13 22:21 UTC, jonathanguven commented on src/lib/components/Login.svelte
> +	const login = () => {
yeah it was from before i switched to form actions

2024-03-13 23:05 UTC, jonathanguven commented on src/routes/+page.server.ts
> +	}
so instead of having /auth and /auth/callback u want just / and /callback?

2024-03-13 23:06 UTC, gursheyss commented on src/routes/+page.server.ts
> +	}
/ and /auth/callback

2024-03-14 01:25 UTC, gursheyss approved these changes

2024-03-15 04:26 UTC, merged